# CMake generated Testfile for 
# Source directory: /Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/GridSearch
# Build directory: /Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/GridSearch
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(FunctionsTest.QuadraticFucntion2d "/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/Build/bin/GridSearch-test" "--gtest_filter=FunctionsTest.QuadraticFucntion2d" "--gtest_color=yes")
set_tests_properties(FunctionsTest.QuadraticFucntion2d PROPERTIES  _BACKTRACE_TRIPLES "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.20/Modules/GoogleTest.cmake;390;add_test;/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/GridSearch/CMakeLists.txt;24;gtest_add_tests;/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/GridSearch/CMakeLists.txt;0;")
add_test(FunctionsTest.QuadraticFucntionNd "/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/Build/bin/GridSearch-test" "--gtest_filter=FunctionsTest.QuadraticFucntionNd" "--gtest_color=yes")
set_tests_properties(FunctionsTest.QuadraticFucntionNd PROPERTIES  _BACKTRACE_TRIPLES "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.20/Modules/GoogleTest.cmake;390;add_test;/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/GridSearch/CMakeLists.txt;24;gtest_add_tests;/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/GridSearch/CMakeLists.txt;0;")
add_test(FunctionsTest.NonConvexFunction2d "/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/Build/bin/GridSearch-test" "--gtest_filter=FunctionsTest.NonConvexFunction2d" "--gtest_color=yes")
set_tests_properties(FunctionsTest.NonConvexFunction2d PROPERTIES  _BACKTRACE_TRIPLES "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.20/Modules/GoogleTest.cmake;390;add_test;/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/GridSearch/CMakeLists.txt;24;gtest_add_tests;/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/GridSearch/CMakeLists.txt;0;")
add_test(GridSearchTests.Grid2dFunction2dGridSearch "/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/Build/bin/GridSearch-test" "--gtest_filter=GridSearchTests.Grid2dFunction2dGridSearch" "--gtest_color=yes")
set_tests_properties(GridSearchTests.Grid2dFunction2dGridSearch PROPERTIES  _BACKTRACE_TRIPLES "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.20/Modules/GoogleTest.cmake;390;add_test;/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/GridSearch/CMakeLists.txt;24;gtest_add_tests;/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/GridSearch/CMakeLists.txt;0;")
add_test(GridSearchTests.GridNdFunctionNdGridSearch "/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/Build/bin/GridSearch-test" "--gtest_filter=GridSearchTests.GridNdFunctionNdGridSearch" "--gtest_color=yes")
set_tests_properties(GridSearchTests.GridNdFunctionNdGridSearch PROPERTIES  _BACKTRACE_TRIPLES "/Applications/CLion.app/Contents/bin/cmake/mac/share/cmake-3.20/Modules/GoogleTest.cmake;390;add_test;/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/GridSearch/CMakeLists.txt;24;gtest_add_tests;/Users/chris/OneDrive/Bern/Semester_01/Applied_Optimization/Exercises/aopt-exercise0/GridSearch/CMakeLists.txt;0;")
